import { PrismaClient, UserRole, PropertyType, PropertyStatus, ListingStatus, RentPeriod } from "@prisma/client";
import { hashPassword } from "@/lib/auth";

const db = new PrismaClient();

async function main() {
  console.log("开始播种数据...");

  const adminPassword = await hashPassword("admin123");
  const landlordPassword = await hashPassword("landlord123");
  const tenantPassword = await hashPassword("tenant123");

  const admin = await db.user.upsert({
    where: { email: "admin@cityrent.com" },
    update: {},
    create: {
      name: "系统管理员",
      email: "admin@cityrent.com",
      password: adminPassword,
      role: UserRole.ADMIN,
      phone: "13800138000",
    },
  });

  const landlord1 = await db.user.upsert({
    where: { email: "landlord@cityrent.com" },
    update: {},
    create: {
      name: "张房东",
      email: "landlord@cityrent.com",
      password: landlordPassword,
      role: UserRole.LANDLORD,
      phone: "13900139000",
      bio: "专业房东，拥有多套优质房源，致力于为租客提供舒适的居住环境。",
    },
  });

  const landlord2 = await db.user.upsert({
    where: { email: "landlord2@cityrent.com" },
    update: {},
    create: {
      name: "李房东",
      email: "landlord2@cityrent.com",
      password: landlordPassword,
      role: UserRole.LANDLORD,
      phone: "13900139001",
      bio: "诚信房东，房源都经过精心装修，欢迎优质租客。",
    },
  });

  const tenant1 = await db.user.upsert({
    where: { email: "tenant@cityrent.com" },
    update: {},
    create: {
      name: "王租客",
      email: "tenant@cityrent.com",
      password: tenantPassword,
      role: UserRole.TENANT,
      phone: "13700137000",
      bio: "IT工程师，爱干净，作息规律。",
    },
  });

  const tenant2 = await db.user.upsert({
    where: { email: "tenant2@cityrent.com" },
    update: {},
    create: {
      name: "刘租客",
      email: "tenant2@cityrent.com",
      password: tenantPassword,
      role: UserRole.TENANT,
      phone: "13700137001",
      bio: "设计师，喜欢安静整洁的环境。",
    },
  });

  console.log("用户数据创建完成");

  const sampleImages = [
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
    "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop",
  ];

  const properties = [
    {
      title: "朝阳区精装修一居室 近地铁",
      description: "房屋位于朝阳区核心地段，步行5分钟即可到达地铁站。小区环境优美，配套设施齐全。房屋为精装修，家电齐全，拎包入住。周边有大型购物中心、医院、学校等配套设施，生活便利。",
      price: 5500,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 11000,
      area: 55,
      bedrooms: 1,
      bathrooms: 1,
      floor: 12,
      totalFloors: 28,
      orientation: "南",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: true,
      hasGarden: false,
      hasPool: false,
      hasGym: true,
      petsAllowed: false,
      smokingAllowed: false,
      address: "朝阳区建国路88号",
      city: "北京",
      district: "朝阳区",
      province: "北京市",
      zipCode: "100022",
      latitude: 39.9087,
      longitude: 116.4474,
      images: sampleImages,
      landlordId: landlord1.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: "海淀区中关村两居室 学区房",
      description: "位于海淀区中关村核心区域，周边教育资源丰富。房屋南北通透，采光良好。小区物业管理完善，24小时安保。临近多家知名互联网公司，通勤便利。",
      price: 8500,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 17000,
      area: 85,
      bedrooms: 2,
      bathrooms: 1,
      floor: 8,
      totalFloors: 18,
      orientation: "南北",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: true,
      hasGarden: false,
      hasPool: false,
      hasGym: false,
      petsAllowed: true,
      smokingAllowed: false,
      address: "海淀区中关村大街1号",
      city: "北京",
      district: "海淀区",
      province: "北京市",
      zipCode: "100080",
      latitude: 39.9842,
      longitude: 116.3074,
      images: sampleImages,
      landlordId: landlord1.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: "浦东新区陆家嘴精装公寓",
      description: "坐落于浦东新区陆家嘴金融中心，江景房，视野开阔。房屋装修豪华，配备高端家电。楼下就是地铁站，交通极为便利。",
      price: 12000,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 24000,
      area: 95,
      bedrooms: 2,
      bathrooms: 2,
      floor: 32,
      totalFloors: 45,
      orientation: "东南",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: true,
      hasGarden: false,
      hasPool: true,
      hasGym: true,
      petsAllowed: false,
      smokingAllowed: false,
      address: "浦东新区陆家嘴环路1000号",
      city: "上海",
      district: "浦东新区",
      province: "上海市",
      zipCode: "200120",
      latitude: 31.2397,
      longitude: 121.4998,
      images: sampleImages,
      landlordId: landlord2.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: "徐汇区温馨一居室",
      description: "徐汇区法租界附近，老上海风情。房屋虽小但五脏俱全，装修温馨舒适。周边文艺气息浓厚，咖啡馆、书店林立。",
      price: 4800,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 4800,
      area: 42,
      bedrooms: 1,
      bathrooms: 1,
      floor: 3,
      totalFloors: 6,
      orientation: "南",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: false,
      hasElevator: false,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasGym: false,
      petsAllowed: true,
      smokingAllowed: false,
      address: "徐汇区衡山路100号",
      city: "上海",
      district: "徐汇区",
      province: "上海市",
      zipCode: "200030",
      latitude: 31.2001,
      longitude: 121.4385,
      images: sampleImages,
      landlordId: landlord2.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: "天河区珠江新城三居室",
      description: "广州CBD核心地段，豪华小区。房屋装修精致，采光极佳。临近珠江，傍晚可沿江散步。周边写字楼林立，上班方便。",
      price: 9500,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 19000,
      area: 110,
      bedrooms: 3,
      bathrooms: 2,
      floor: 25,
      totalFloors: 39,
      orientation: "南",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: true,
      hasGarden: true,
      hasPool: true,
      hasGym: true,
      petsAllowed: false,
      smokingAllowed: false,
      address: "天河区珠江新城华夏路8号",
      city: "广州",
      district: "天河区",
      province: "广东省",
      zipCode: "510623",
      latitude: 23.1291,
      longitude: 113.3280,
      images: sampleImages,
      landlordId: landlord1.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: true,
    },
    {
      title: "南山区科技园LOFT公寓",
      description: "深圳南山区科技园，专为IT人士打造。LOFT格局，空间利用率高。小区年轻人多，氛围活跃。步行即可到达各大互联网公司。",
      price: 6800,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 13600,
      area: 65,
      bedrooms: 1,
      bathrooms: 1,
      floor: 15,
      totalFloors: 22,
      orientation: "南",
      type: PropertyType.LOFT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasGym: true,
      petsAllowed: true,
      smokingAllowed: false,
      address: "南山区科技园科苑路16号",
      city: "深圳",
      district: "南山区",
      province: "广东省",
      zipCode: "518057",
      latitude: 22.5431,
      longitude: 113.9413,
      images: sampleImages,
      landlordId: landlord2.id,
      status: PropertyStatus.PENDING,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: "西湖区文教区精装两居",
      description: "杭州西湖区，毗邻浙江大学。文化氛围浓厚，周边配套完善。房屋保养良好，家电家具齐全，拎包入住。",
      price: 5200,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 10400,
      area: 78,
      bedrooms: 2,
      bathrooms: 1,
      floor: 6,
      totalFloors: 11,
      orientation: "南北",
      type: PropertyType.APARTMENT,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: true,
      hasGarden: false,
      hasPool: false,
      hasGym: false,
      petsAllowed: false,
      smokingAllowed: false,
      address: "西湖区文三路235号",
      city: "杭州",
      district: "西湖区",
      province: "浙江省",
      zipCode: "310012",
      latitude: 30.2741,
      longitude: 120.1551,
      images: sampleImages,
      landlordId: landlord1.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: false,
    },
    {
      title: "锦江区春熙路时尚开间",
      description: "成都市中心春熙路商圈，地理位置绝佳。开间设计，现代简约风格。楼下就是地铁站，逛街购物方便至极。",
      price: 3800,
      rentPeriod: RentPeriod.MONTHLY,
      deposit: 3800,
      area: 38,
      bedrooms: 1,
      bathrooms: 1,
      floor: 18,
      totalFloors: 30,
      orientation: "东",
      type: PropertyType.STUDIO,
      furnished: true,
      hasParking: true,
      hasElevator: true,
      hasBalcony: false,
      hasGarden: false,
      hasPool: false,
      hasGym: true,
      petsAllowed: false,
      smokingAllowed: false,
      address: "锦江区春熙路东段1号",
      city: "成都",
      district: "锦江区",
      province: "四川省",
      zipCode: "610016",
      latitude: 30.6570,
      longitude: 104.0650,
      images: sampleImages,
      landlordId: landlord2.id,
      status: PropertyStatus.APPROVED,
      listingStatus: ListingStatus.ACTIVE,
      isFeatured: true,
    },
  ];

  for (const propertyData of properties) {
    await db.property.upsert({
      where: { id: `seed_${propertyData.title}` },
      update: {},
      create: {
        ...propertyData,
        id: undefined,
        price: propertyData.price as any,
        deposit: propertyData.deposit as any,
        latitude: propertyData.latitude as any,
        longitude: propertyData.longitude as any,
      },
    });
  }

  console.log("房源数据创建完成");
  console.log("播种完成！");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
